#!/usr/bin/env python
# vim: set fileencoding=utf-8 filetype=python :
import logging
logging.basicConfig()
log = logging.getLogger()
import sys

import requests

URL = 'http://euw.lolesports.com/vods/'

resp = requests.get(URL)
if resp.status_code != 200:
    log.warn('Could not fetch')
print resp.content
