#!/usr/bin/env python
# vim: set fileencoding=utf-8 filetype=python :
import logging
logging.basicConfig()
log = logging.getLogger()
import sys

import requests

import os
import errno


match_ids = sys.argv[1:]


def mkdir_p(path):
    try:
        os.makedirs(path)
    except OSError as exc:
        if exc.errno == errno.EEXIST and os.path.isdir(path):
            pass
        else:
            raise

mkdir_p('matches')

for match_id in match_ids:
    url = 'http://euw.lolesports.com/tourney/match/%s' % match_id
    log.info(url)
    resp = requests.get(url)
    if resp.status_code != 200:
        log.warn('could not fetch match %s' % match_id)
        continue
    fname = 'matches/%s.html' % match_id
    with open(fname, 'w') as f:
        f.write(resp.content)
