#!/usr/bin/env python
# vim: set fileencoding=utf-8 filetype=python :
import logging
logging.basicConfig()
log = logging.getLogger()
import sys
from lxml import etree

fname = sys.argv[1]

parser = etree.HTMLParser()
doc = etree.parse(fname, parser)

for e in doc.xpath('//a[contains(@href, "nojs")]'):
    print e.get('href')
